Repository leo-editor/leo-editor, pull requests merged in 2021-05, with the labels that each got.

#1917 PR: Fix pyflakes complaints
  leo/commands/commanderFileCommands.py
  leo/commands/editFileCommands.py
  leo/core/leoApp.py
  leo/core/leoAst.py
  leo/core/leoAtFile.py
  leo/core/leoFastRedraw.py
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/core/leoPlugins.py
  leo/core/leoRst.py
  leo/core/leoserver.py
  leo/plugins/free_layout.py
Labels: PullRequest

#1920 PR: beautify all files
  leo/commands/baseCommands.py
  leo/commands/checkerCommands.py
  leo/commands/commanderEditCommands.py
  leo/commands/commanderFileCommands.py
  leo/commands/commanderOutlineCommands.py
  leo/commands/editCommands.py
  leo/commands/editFileCommands.py
  leo/commands/searchCommands.py
  leo/core/leoApp.py
  leo/core/leoAst.py
  leo/core/leoAtFile.py
  leo/core/leoColorizer.py
  leo/core/leoCommands.py
  leo/core/leoExternalFiles.py
  leo/core/leoFileCommands.py
  leo/core/leoFind.py
  leo/core/leoFrame.py
  leo/core/leoGlobals.py
  leo/core/leoGui.py
  leo/core/leoIPython.py
  leo/core/leoImport.py
  leo/core/leoKeys.py
  leo/core/leoMenu.py
  leo/core/leoNodes.py
  leo/core/leoRst.py
  leo/core/leoTest.py
  leo/core/leoTest2.py
  leo/core/leoUndo.py
  leo/core/leoVim.py
  leo/plugins/free_layout.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_text.py
  leo/plugins/qt_tree.py
  leo/test/leo-bridge-test.py
  leo/unittests/commands/test_editCommands.py
  leo/unittests/core/test_leoNodes.py
Labels: PullRequest

#1922 PR for #1919: width of hard tabs
  leo/core/leoColorizer.py
Labels: PullRequest

#1915 PR for #1914: use g.fullPath
  leo/commands/checkerCommands.py
  leo/commands/commanderFileCommands.py
  leo/commands/editFileCommands.py
  leo/core/leoAtFile.py
  leo/core/leoCommands.py
  leo/core/leoExternalFiles.py
  leo/core/leoFileCommands.py
  leo/core/leoGlobals.py
  leo/core/leoImport.py
  leo/core/leoPersistence.py
  leo/core/leoShadow.py
  leo/plugins/add_directives.py
  leo/plugins/lineNumbers.py
  leo/plugins/niceNosent.py
  leo/plugins/open_shell.py
  leo/plugins/qt_frame.py
  leo/plugins/vim.py
  leo/test/activeUnitTests.txt
  leo/test/unitTest.leo
  leo/unittests/commands/test_editCommands.py
Labels: Enhancement

#1924 PR: Clean plugins
  leo/plugins/FileActions.py
  leo/plugins/anki.py
  leo/plugins/at_folder.py
  leo/plugins/at_view.py
  leo/plugins/chapter_hoist.py
  leo/plugins/datenodes.py
  leo/plugins/dragdropgoodies.py
  leo/plugins/dtest.py
  leo/plugins/dump_globals.py
  leo/plugins/empty_leo_file.py
  leo/plugins/enable_gc.py
  leo/plugins/examples/chinese_menu.py
  leo/plugins/examples/french_fm.py
  leo/plugins/examples/override_classes.py
  leo/plugins/examples/override_commands.py
  leo/plugins/examples/redefine_put.py
  leo/plugins/expfolder.py
  leo/plugins/geotag.py
  leo/plugins/history_tracer.py
  leo/plugins/initinclass.py
  leo/plugins/jinjarender.py
  leo/plugins/leoPluginNotes.txt
  leo/plugins/leo_pdf.py
  leo/plugins/leo_to_html.py
  leo/plugins/line_numbering.py
  leo/plugins/macros.py
  leo/plugins/maximizeNewWindows.py
  leo/plugins/mnplugins.py
  leo/plugins/mod_leo2ascd.py
  leo/plugins/mod_leo2ascd.txt
  leo/plugins/mod_read_dir_outline.py
  leo/plugins/mod_scripting.py
  leo/plugins/mod_timestamp.py
  leo/plugins/nodeActions.py
  leo/plugins/nodediff.py
  leo/plugins/outline_export.py
  leo/plugins/paste_as_headlines.py
  leo/plugins/plugins_menu.py
  leo/plugins/quickMove.py
  leo/plugins/rss.py
  leo/plugins/run_nodes.py
  leo/plugins/screenshots.py
  leo/plugins/script_io_to_body.py
  leo/plugins/sftp.py
  leo/plugins/slideshow.py
  leo/plugins/systray.py
  leo/plugins/test/failed_to_load_plugin.py
  leo/plugins/textnode.py
  leo/plugins/trace_gc_plugin.py
  leo/plugins/trace_keys.py
  leo/plugins/viewrendered2.py
  leo/plugins/vim.py
  leo/plugins/wikiview.py
  leo/plugins/word_count.py
  leo/plugins/word_export.py
  leo/plugins/xemacs.py
  leo/plugins/xsltWithNodes.py
Labels: PullRequest

#1881 PR for #1846, ekr-qt branch
  leo/core/LeoPyRef.leo
  leo/core/leoColorizer.py
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/core/leoPrinting.py
  leo/core/leoQt.py
  leo/core/leoQt4.py
  leo/core/leoQt5.py
  leo/core/leoQt6.py
  leo/doc/LeoDocs.leo
  leo/modes/sql.py
  leo/plugins/QNCalendarWidget.py
  leo/plugins/ToDo.ui
  leo/plugins/attrib_edit.py
  leo/plugins/bigdash.py
  leo/plugins/bookmarks.py
  leo/plugins/ctagscompleter.py
  leo/plugins/demo.py
  leo/plugins/dragdropgoodies.py
  leo/plugins/editpane/clicky_splitter.py
  leo/plugins/editpane/editpane.py
  leo/plugins/editpane/plaintextedit.py
  leo/plugins/editpane/webkitview.py
  leo/plugins/free_layout.py
  leo/plugins/ftp.py
  leo/plugins/graphcanvas.py
  leo/plugins/nav_qt.py
  leo/plugins/nested_splitter.py
  leo/plugins/nodetags.py
  leo/plugins/notebook.py
  leo/plugins/pyplot_backend.py
  leo/plugins/python_terminal.py
  leo/plugins/qt_commands.py
  leo/plugins/qt_events.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_gui.py
  leo/plugins/qt_quicksearch.py
  leo/plugins/qt_quicksearch_sub.py
  leo/plugins/qt_text.py
  leo/plugins/qt_tree.py
  leo/plugins/quickMove.py
  leo/plugins/quicksearch.py
  leo/plugins/screen_capture.py
  leo/plugins/screencast.py
  leo/plugins/screenshots.py
  leo/plugins/stickynotes.py
  leo/plugins/stickynotes_plus.py
  leo/plugins/systray.py
  leo/plugins/threadutil.py
  leo/plugins/todo.py
  leo/plugins/viewrendered.py
  leo/plugins/viewrendered2.py
  leo/plugins/viewrendered3.py
  leo/plugins/wikiview.py
  leo/plugins/xdb_pane.py
Labels: PullRequest

#1929 small correction for Qt6 import
  leo/core/leoQt6.py
Labels: PullRequest

#1931 PR for #1930
  leo/commands/commanderFileCommands.py
  leo/core/leoImport.py
  leo/plugins/qt_frame.py
Labels: PullRequest

#1927 PR for #1926: size of LeoPyRef.leo
  leo/core/LeoPyRef.leo
  leo/modes/forth.py
  leo/plugins/QNCalendarWidget.py
  leo/plugins/anki.py
  leo/plugins/leo_cloud.py
  leo/plugins/leo_cloud_server.py
  leo_to_html.xsl
  run_travis_unit_tests.py
Labels: PullRequest

#1935 PR for #1933
  leo/commands/editCommands.py
  leo/core/leoKeys.py
  leo/core/leoQt.py
  leo/plugins/qt_events.py
  leo/plugins/qt_frame.py
Labels: PullRequest

#1937 PR for both #1933 and #1722.
  flake8-leo.py
  leo/commands/commanderFileCommands.py
  leo/core/leoApp.py
  leo/core/leoCommands.py
  leo/core/leoFileCommands.py
  leo/plugins/qt_frame.py
  pyflakes-leo.py
Labels: PullRequest

#1938 PR for #1934
  leo/plugins/viewrendered3.py
Labels: PullRequest

#1940 Report number of unchanged files
  leo/core/leoAtFile.py
Labels: PullRequest

#1943 Fix #1942
  leo/plugins/stickynotes.py
Labels: PullRequest

#1945 PR for #1944
  .mypy.ini
  leo/commands/editFileCommands.py
  leo/core/leoAst.py
  leo/plugins/leo_mypy_plugin.py
  leo/plugins/qt_gui.py
Labels: PullRequest

#1947 PR for #1946: g.assertUi
  leo/plugins/QNCalendarWidget.py
  leo/plugins/attrib_edit.py
  leo/plugins/auto_colorize2_0.py
  leo/plugins/bigdash.py
  leo/plugins/bookmarks.py
  leo/plugins/bzr_qcommands.py
  leo/plugins/contextmenu.py
  leo/plugins/ctagscompleter.py
  leo/plugins/demo.py
  leo/plugins/dragdropgoodies.py
  leo/plugins/free_layout.py
  leo/plugins/ftp.py
  leo/plugins/graphcanvas.py
  leo/plugins/history_tracer.py
  leo/plugins/leo_cloud.py
  leo/plugins/leo_mypy_plugin.py
  leo/plugins/line_numbering.py
  leo/plugins/livecode.py
  leo/plugins/mod_autosave.py
  leo/plugins/nav_qt.py
  leo/plugins/nodetags.py
  leo/plugins/nodewatch.py
  leo/plugins/notebook.py
  leo/plugins/projectwizard.py
  leo/plugins/python_terminal.py
  leo/plugins/qt_text.py
  leo/plugins/quickMove.py
  leo/plugins/quicksearch.py
  leo/plugins/richtext.py
  leo/plugins/screen_capture.py
  leo/plugins/screencast.py
  leo/plugins/screenshots.py
  leo/plugins/sftp.py
  leo/plugins/spydershell.py
  leo/plugins/stickynotes.py
  leo/plugins/stickynotes_plus.py
  leo/plugins/systray.py
  leo/plugins/threadutil.py
  leo/plugins/todo.py
  leo/plugins/viewrendered.py
  leo/plugins/viewrendered2.py
  leo/plugins/viewrendered3.py
  leo/plugins/wikiview.py
  leo/plugins/xdb_pane.py
  leo/test/activeUnitTests.txt
Labels: PullRequest

#1956 PR for #1955: extract command
  leo/commands/commanderEditCommands.py
  leo/test/activeUnitTests.txt
Labels: PullRequest

#1957 Make sftm.init_widgets more robust
  leo/core/leoGui.py
Labels: PullRequest

#1958 PR for #1907
  leo/core/leoAtFile.py
Labels: PullRequest

#1954 PR for #1953: Qt6 dialogs
  leo/plugins/qt_gui.py
Labels: Draft, PullRequest

#1962 PR for #1961
  leo/core/leoExternalFiles.py
Labels: PullRequest

#1963 Correct imports in tests
  leoclient.py
  leoserver.py
Labels: PullRequest
