Repository leo-editor/leo-editor, pull requests merged in 2022-05, with the labels that each got.

#2632 mypy fixes/suppressions
  leo/core/leoQt5.py
  leo/core/leoQt6.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_gui.py
  leo/plugins/qt_text.py
  leo/plugins/qt_tree.py
Labels: PullRequest

#2639 PR for #2638: test-all
  leo/core/leoGlobals.py
Labels: PullRequest

#2654 PR for #2653: Remove pyflakes-leo.py and g.LinterTable class
  leo/core/leoGlobals.py
  leo/doc/leoAttic.txt
  pyflakes-leo.py
Labels: PullRequest

#2655 PR for #2645: flash when opening the workbook
  leo/core/leoApp.py
Labels: PullRequest

#2658 PR for #2657: pastable pyflakes error messages
  leo/core/leoFrame.py
  leo/core/leoGlobals.py
  leo/unittests/test_gui.py
Labels: PullRequest

#2659 PR: Remove 'fileName' arg from readExternalFiles
  leo/core/leoFileCommands.py
Labels: PullRequest

#2660 Allow .leojs files in save-as dialog
  leo/commands/commanderFileCommands.py
Labels: PullRequest

#2661 PR for #2642: console gui delete bug
  leo/plugins/cursesGui2.py
Labels: PullRequest

#2646 Fix vr3 handling of missing markdown, remove old webkit import workarounds
  leo/plugins/viewrendered3.py
Labels: PullRequest

#2664 Fix VR unable to render @jupyter nodes.
  leo/plugins/viewrendered.py
Labels: Bug

#2665 Tbp find pane
  leo/core/leoFind.py
  leo/core/leoGui.py
  leo/plugins/qt_frame.py
Labels: Enhancement
