Repository leo-editor/leo-editor, pull requests merged in 2022-11, with the labels that each got.

#2953 PR for #2952: Capitalize 'position'
  leo/plugins/cursesGui.py
  leo/plugins/leoflexx.py
Labels: Code, PullRequest

#2962 PR for #2950
  leo/commands/editFileCommands.py
Labels: Bug

#2969 Fix typos that disabled two guards
  leo/core/leoGui.py
  leo/plugins/qt_gui.py
Labels: Code

#2974 Added support for Dart language. Version to 3.88.
  leo/plugins/viewrendered3.py
Labels: Enhancement

#2981 PR: Fix bugs in modes/batch.py
  leo/modes/batch.py
Labels: Enhancement, PullRequest
