Repository leo-editor/leo-editor, pull requests merged in 2022-12, with the labels that each got.

#2986 PR: Fix problems with read-ref-file
  leo/core/leoFileCommands.py
Labels: Bug, PullRequest

#2987 PR Improve coloring of .cmd files
  leo/core/leoApp.py
  leo/modes/batch.py
Labels: Enhancement, PullRequest

#2985 PR2 for #2983: support --black-sentinels
  leo/commands/abbrevCommands.py
  leo/commands/editCommands.py
  leo/commands/gotoCommands.py
  leo/commands/helpCommands.py
  leo/core/leoApp.py
  leo/core/leoAst.py
  leo/core/leoAtFile.py
  leo/core/leoChapters.py
  leo/core/leoColorizer.py
  leo/core/leoExternalFiles.py
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/core/leoIPython.py
  leo/core/leoKeys.py
  leo/core/leoTest2.py
  leo/core/leoserver.py
  leo/plugins/leoflexx.py
  leo/plugins/screen_capture.py
  leo/unittests/commands/test_convertCommands.py
  leo/unittests/core/test_leoAst.py
  leo/unittests/core/test_leoAtFile.py
  leo/unittests/core/test_leoColorizer.py
  leo/unittests/core/test_leoGlobals.py
  leo/unittests/core/test_leoNodes.py
  leo/unittests/test_importers.py
Labels: Enhancement, PullRequest

#2997 PR for #2996: serious bug in @clean
  leo/core/leoAtFile.py
Labels: Bug, PullRequest

#2998 PR: Improve search for pylint's configuration file
  leo/commands/checkerCommands.py
Labels: Enhancement

#2993 Update viewrendered3.py
  leo/plugins/viewrendered3.py
Labels: Enhancement, PullRequest

#3009 PR for #3008: Leo doesn't start with --gui=console
  leo/plugins/cursesGui2.py
Labels: Bug, PullRequest

#3012 PR for #3010: show-file-line
  leo/commands/gotoCommands.py
Labels: Bug, PullRequest

#3016 Change time.clock() to time.time_ns() since time.clock() no longer exists
  leo/scripts/leoScripts.txt
Labels: Bug

#3020 PR for #3017: failing unit test
  leo/unittests/test_plugins.py
Labels: Bug, Testing
