Repository leo-editor/leo-editor, pull requests merged in 2022-10, with the labels that each got.

#2904 PR: use 'newHeadline' for all new headlines
  leo/core/leoFrame.py
  leo/plugins/cursesGui.py
Labels: Enhancement, PullRequest

#2908 Delete unused init_ivars_from_settings method
  leo/core/leoFind.py
Labels: PullRequest

#2915 PR for #2914: Retire old window code
  leo/config/leoSettings.leo
  leo/doc/leoAttic.txt
  leo/plugins/leo_babel/babel_lib.py
  leo/plugins/qt_frame.py
Labels: Bug, PullRequest

#2918 Make sure Markdown writers insert just a single space after the headline
  leo/plugins/viewrendered3.py
  leo/plugins/writers/markdown.py
Labels: Bug, PullRequest

#2923 PR for #2922: markdown unit tests
  leo/unittests/test_importers.py
Labels: Code, PullRequest

#2916 PR for #2906: focus problem
  leo/doc/LeoDocs.leo
Labels: Bug, PullRequest

#2924 PR for #2917: redundant code
  leo/core/leoAtFile.py
Labels: Code, PullRequest

#2925 PR for #2920: Fix/delete dubious code in leoFind.py
  leo/core/leoFind.py
  leo/unittests/core/test_leoFind.py
Labels: Code, PullRequest

#2926 PR for #2910: pane commands
  leo/plugins/pane_commands.py
Labels: Enhancement, PullRequest

#2930 Fix LM.traceShortcutsDict()
  leo/core/leoApp.py
Labels: Bug, PullRequest

#2932 PR: fix 'invisible' bug in leoFind.change_selection
  leo/core/leoFind.py
Labels: Code, PullRequest

#2934 PR for #2933: typescript coloring glitch
  leo/core/leoColorizer.py
Labels: Bug

#2935 PR: Replace precompile_pattern with compile_pattern
  leo/core/leoFind.py
Labels: Code, PullRequest

#2936 leoServer: Fixed node commands that add/insert a node to be used in context menu from another node. (and return to selection)
  leo/core/leoserver.py
Labels: Enhancement

#2940 Merge felix-server5 into devel: improved leoserver client pgUp/Down functionality
  leo/core/leoserver.py
Labels: Enhancement

#2941 PR: Delete flush-lines and keep-lines commands
  leo/commands/editCommands.py
  leo/doc/LeoDocs.leo
  leo/doc/leoAttic.txt
Labels: Enhancement, PullRequest

#2942 PR: Improve handling of backspace during auto-completion
  leo/core/leoKeys.py
  leo/doc/leoAttic.txt
Labels: Enhancement, PullRequest

#2944 leoserver.py: added get_branch for current opened document
  leo/core/leoserver.py
Labels: Enhancement
