Repository leo-editor/leo-editor, pull requests merged in 2022-09, with the labels that each got.

#2787 PR: Require Python 3.9 or above
  leo/core/leoGlobals.py
Labels: PullRequest

#2790 Remove version warning in python importer
  leo/plugins/importers/python.py
Labels: Code, PullRequest

#2794 PR for #2793: crash in mod_scripting
  leo/plugins/mod_scripting.py
Labels: Bug, PullRequest

#2795 PR: Remove obsolete tests of python version
  leo/unittests/core/test_leoAtFile.py
  leo/unittests/test_importers.py
Labels: Code

#2802 PR: for #2800: crash with --trace=events
  leo/plugins/qt_events.py
Labels: Bug, PullRequest

#2803 PR 2 for #2799: performance bug
  leo/commands/editCommands.py
  leo/core/leoFrame.py
  leo/plugins/qt_tree.py
Labels: Bug, PullRequest

#2807 Fix annotations for todo.py
  leo/plugins/todo.py
Labels: Code, PullRequest

#2809 PR: Add 'diff:' to all diff nodes
  leo/commands/editFileCommands.py
Labels: Enhancement, PullRequest

#2811 PR: Fix serious bug in PR #1809: do *not* append 'diff:' to cloned headlines!
  leo/commands/editFileCommands.py
Labels: Bug, PullRequest

#2820 PR: Fix a Qt6 crash
  leo/core/leoPrinting.py
Labels: Bug, PullRequest

#2821 fix JSON encoded user attribute error handling to make mypy happy
  leo/core/leoFileCommands.py
Labels: PullRequest

#2816 fix Declutter REPLACE-REST
  leo/plugins/qt_tree.py
Labels: PullRequest

#2823 fix #2822
  leo/plugins/qt_text.py
Labels: Bug, PullRequest

#2833 add py.typed to leo package
  leo/py.typed
Labels: Code, PullRequest

#2836 PR for #2825: test qt imports
  leo/core/leoQt6.py
  leo/unittests/core/test_leoQt6.py
Labels: Code, PullRequest

#2841 PR: Remove unnecesssary arguments-differ suppressions
  leo/core/leoDebugger.py
  leo/plugins/importers/javascript.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_gui.py
Labels: Code, PullRequest

#2842 PR: Simplify and improve g.objectToString
  leo/core/leoGlobals.py
Labels: Enhancement, PullRequest

#2845 Add warning to NodeIndices.computeNewIndex
  leo/core/leoNodes.py
Labels: Documentation, PullRequest

#2850 PR for #2770: Suppress the deprecation warning in leoservers.py
  leo/core/leoserver.py
Labels: Bug, PullRequest

#2851 PR for #2847: dependabot error
  leo/plugins/pygeotag/package.json
Labels: PullRequest

#2854 PR 2 for #2793: mod_scripting crash
  leo/plugins/mod_scripting.py
Labels: Bug

#2859 PR: Fully annotate leo.plugins.qt_tree
  leo/plugins/qt_tree.py
Labels: Code, PullRequest

#2865 Reintroduce type:ignore to handle tricky type (and fix a crash!)
  leo/commands/checkerCommands.py
Labels: Bug, PullRequest

#2869 PR for #2866: unwanted message
  leo/core/leoQt6.py
Labels: Enhancement, PullRequest

#2874 Add pylint disable statements.
  leo/plugins/freewin.py
Labels: Enhancement

#2876 Added type annotations to freewin.py.
  leo/plugins/freewin.py
Labels: Enhancement

#2880 PR for #2878: remove c.redraw_after_icons_changed
  leo/commands/bufferCommands.py
  leo/commands/commanderEditCommands.py
  leo/commands/commanderFileCommands.py
  leo/commands/commanderOutlineCommands.py
  leo/commands/editCommands.py
  leo/core/leoCommands.py
  leo/core/leoFileCommands.py
  leo/core/leoFrame.py
  leo/core/leoUndo.py
  leo/plugins/contextmenu.py
  leo/plugins/cursesGui2.py
  leo/plugins/freewin.py
Labels: Code

#2881 PR: Remove unused test files
  .mypy.ini
  leo/core/LeoPyRef.leo
  leo/core/leoBridgeTest.py
  leo/core/leoDynamicTest.py
Labels: Code, PullRequest

#2888 Needed to make running a subtree with an external processor
  leo/plugins/viewrendered3.py
Labels: Bug

#2890 PR for #2889: crash in nav_qt.py
  leo/plugins/nav_qt.py
Labels: Bug, PullRequest

#2893 PR: fix crash in python importer
  leo/plugins/importers/python.py
Labels: Bug, PullRequest

#2896 PR for #2895: g.get_directives_dict
  leo/core/leoGlobals.py
Labels: Code, PullRequest
