Repository leo-editor/leo-editor, pull requests merged in 2023-09, with the labels that each got.

#3523 PR for #3521: what-line
  leo/commands/editCommands.py
Labels: Bug, PullRequest

#3525 PR for #3522: promote-section-definition command
  leo/commands/editCommands.py
Labels: Enhancement, PullRequest

#3535 PR for #3533: revert instead of reload
  leo/core/leoApp.py
  leo/core/leoExternalFiles.py
Labels: Enhancement

#3537 git-diff now makes a diff tree for .leojs files, as it already does for .leo file.
  leo/commands/editFileCommands.py
Labels: PullRequest

#3539 Made 'file-diff-files' undoable. Also made it insert it's diff result node at the end like other 'diff' & 'find-all' commands.
  leo/commands/editFileCommands.py
Labels: PullRequest

#3544 PR: Prepare leoSettings.leo for 6.7.5.
  leo/config/leoSettings.leo
Labels: Pip, PullRequest

#3549 Fix message in the 'ask' method of leoserver for .leojs files when change is detected.
  leo/core/leoserver.py
Labels: Enhancement

#3552 PR for #3550: clear the dirty bit when writing sqLite dbs
  leo/core/leoFileCommands.py
Labels: Bug, PullRequest

#3556 PR for #3555
  leo/plugins/importers/base_importer.py
Labels: Code, PullRequest

#3557 PR Add BaseWriter.write method
  leo/plugins/writers/basewriter.py
Labels: Code, PullRequest

#3561 PR for #3560: Retire Sherlock
  leo/core/leoGlobals.py
  leo/doc/leoAttic.txt
  leo/unittests/core/test_leoAst.py
Labels: Code, PullRequest

#3564 PR: Spell-check importer and writer files
  leo/plugins/importers/base_importer.py
  leo/plugins/importers/dart.py
  leo/plugins/importers/java.py
  leo/plugins/importers/leo_rst.py
  leo/plugins/importers/lua.py
  leo/plugins/importers/markdown.py
  leo/plugins/importers/org.py
  leo/plugins/importers/otl.py
  leo/plugins/importers/pascal.py
  leo/plugins/importers/php.py
  leo/plugins/importers/python.py
  leo/plugins/importers/tcl.py
  leo/plugins/importers/xml.py
Labels: Code, PullRequest

#3565 PR: Fix module-level docstring for dart writer
  leo/plugins/writers/dart.py
Labels: Code, PullRequest

#3571 PR: Ignore only non-alpha words in http lines
  leo/commands/spellCommands.py
Labels: Enhancement, Code

#3573 PR: Fix quirp in a unit test
  leo/unittests/core/test_leoImport.py
Labels: Code, PullRequest

#3581 PR: Change print-size setting to pixels
  leo/config/leoSettings.leo
  leo/core/leoPrinting.py
Labels: Enhancement

#3585 PR for #3584: Fix annotations for controller and button
  leo/core/leoFrame.py
  leo/plugins/qt_frame.py
Labels: Code, PullRequest
