Repository leo-editor/leo-editor, pull requests merged in 2023-10, with the labels that each got.

#3589 Fix two docstrings and related annotations
  leo/core/leoConfig.py
Labels: Code

#3595 PR for #3588: word-search
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/unittests/core/test_leoGlobals.py
Labels: Bug, PullRequest

#3599 Boltex/issue3587
  leo/core/leoserver.py
Labels: Enhancement

#3608 PR: Fix two importer quirps
  leo/unittests/test_importers.py
Labels: Code, PullRequest

#3605 PR for #3604: startup message
  leo/core/leoApp.py
  leo/core/leoGui.py
  leo/core/leoQt.py
  leo/core/leoTest2.py
  leo/core/runLeo.py
  leo/plugins/nodetags.py
  leo/unittests/core/test_leoColorizer.py
  leo/unittests/test_gui.py
Labels: Bug, PullRequest, Testing

#3607 PR for #3606: scheme importer
  leo/core/leoApp.py
  leo/core/leoColorizer.py
  leo/modes/scheme.py
  leo/plugins/importers/base_importer.py
  leo/plugins/importers/elisp.py
  leo/plugins/importers/scheme.py
  leo/unittests/test_importers.py
Labels: Enhancement

#3612 PR for #3603: `pip install leo` fails with Python 3.12
  setup.py
Labels: Pip, PullRequest

#3621 PR for #3620: importer bugs
  leo/plugins/importers/base_importer.py
  leo/plugins/importers/javascript.py
  leo/unittests/test_importers.py
Labels: Bug, PullRequest, leoJS

#3625 PR for #3624: crash in rust importer
  leo/plugins/importers/base_importer.py
Labels: Bug

#3618 PR: Fix quirp in check_outline
  leo/plugins/importers/base_importer.py
Labels: Code, leoJS

#3614 Replace lost "@" character when command line option "--load-type" is processed
  leo/core/leoApp.py
Labels: Bug
