Repository leo-editor/leo-editor, pull requests merged in 2023-02, with the labels that each got.

#3127 PR: Make g.trace work like legacy version
  leo/core/leoGlobals.py
Labels: Code, PullRequest

#3130 PR for #3126: tracing_utils.py
  leo/core/tracing_utils.py
Labels: Code, PullRequest

#3128 PR for #3124: improve ctrl-click searches
  leo/commands/spellCommands.py
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_text.py
  leo/scripts/test-one-leo.cmd
  leo/unittests/core/test_leoFind.py
Labels: Enhancement, PullRequest

#3132 PR Add support for @bool rst3-remove-leo-directives
  leo/config/leoSettings.leo
  leo/core/leoRst.py
Labels: Enhancement

#3135 PR: Remove all traces of find-all-unique-regex
  leo/core/leoFind.py
  leo/core/leoserver.py
  leo/doc/LeoDocs.leo
  leo/unittests/core/test_leoFind.py
Labels: Code, PullRequest

#3136 PR: Remove LeoFind.unique_matches
  leo/core/leoFind.py
  leo/unittests/core/test_leoFind.py
Labels: Code, PullRequest

#3144 Use keyword-only kwargs in the leoAst.LeoGlobals class
  leo/core/leoAst.py
Labels: Code, PullRequest

#3145 Excessive Save Time (issue 3143): when saving an outline, only clear …
  leo/core/leoCommands.py
Labels: Bug, Performance

#3147 openUrlHelper: define found_gnx first to avoid use-before-set error.
  leo/core/leoGlobals.py
Labels: Bug

#3148 commanderOutlineCommands (issue #3146): Keep original node focus after outline expansion
  leo/commands/commanderOutlineCommands.py
Labels: Bug

#3151 plugins: Fix regularizeName() to work with either '.py' or '.pyw' extensions
  leo/core/leoPlugins.py
Labels: Bug

#3154 Themes: Update theme tbp_dark.leo
  leo/themes/tbp_dark.leo
Labels: Enhancement

#3164 PR: Replace settings.match_word with whole_word
  leo/unittests/core/test_leoFind.py
Labels: PullRequest, Testing

#3160 PR: improve check-nodes command
  leo/commands/checkerCommands.py
  leo/core/leoGlobals.py
  leo/scripts/test-one-leo.cmd
  leo/unittests/commands/test_checkerCommands.py
Labels: Enhancement, PullRequest

#3167 PR: prev-slide does nothing when at first slide
  leo/plugins/picture_viewer.py
Labels: Enhancement, PullRequest

#3171 PR for #3170: scrolling in the picture_viewer plugin
  leo/plugins/picture_viewer.py
Labels: Bug, PullRequest
