Repository leo-editor/leo-editor, pull requests merged in 2023-08, with the labels that each got.

#3478 PR for #3476: diff-marked-nodes
  leo/core/leoCompare.py
  leo/unittests/core/test_leoCompare.py
Labels: Bug

#3489 Fixed docstring of tag-node and tag-children.
  leo/core/leoFind.py
Labels: Anomaly

#3494 Fixes readFileIntoNode and import_txt_file.
  leo/commands/commanderFileCommands.py
  leo/core/leoApp.py
Labels: Bug

#3491 Fixed 'goto-prev-marked' docstring.
  leo/commands/commanderOutlineCommands.py
Labels: Anomaly

#3501 PR for #3500: Remove all code from the attic
  leo/doc/leoAttic.txt
Labels: PullRequest

#3511 PR for #3510: fix syntax coloring for rust
  leo/modes/rust.py
Labels: Bug, lvl:minor, PullRequest
