Repository leo-editor/leo-editor, pull requests merged in 2023-04, with the labels that each got.

#3242 PR for #3240: qt crash
  leo/plugins/nested_splitter.py
Labels: Bug, PullRequest

#3239 PR for #3234: undefined section color
  leo/config/leoSettings.leo
Labels: Bug, PullRequest

#3241 PR for #3235: path wrappers
  leo/commands/checkerCommands.py
  leo/commands/convertCommands.py
  leo/core/leoAtFile.py
  leo/core/leoBeautify.py
  leo/core/leoCommands.py
  leo/core/leoDebugger.py
  leo/core/leoExternalFiles.py
  leo/core/leoGlobals.py
  leo/core/leoImport.py
  leo/core/leoserver.py
  leo/plugins/niceNosent.py
  leo/plugins/open_shell.py
  leo/plugins/vim.py
  leo/unittests/core/test_leoAtFile.py
Labels: Code, PullRequest

#3250 PR: Simplify qtree.drawChildren
  leo/plugins/qt_tree.py
Labels: Code, PullRequest

#3251 VR3: open in log pane
  leo/plugins/viewrendered3.py
Labels: PullRequest

#3254 PR for #3262: Change @solarized-purple to @solarized-violet in all theme files
  leo/themes/DefaultTheme.leo
  leo/themes/EKRDark.leo
  leo/themes/LeoBlackSolarized.leo
  leo/themes/minimal-ui-tbp_dark_solarized.leo
  leo/themes/minimal-ui-tbp_light_solarized.leo
  leo/themes/tbp_dark.leo
  leo/themes/tbp_dark_solarized.leo
  leo/themes/tbp_light.leo
  leo/themes/tbp_light_quasi_solarized.leo
  leo/themes/tbp_light_solarized.leo
Labels: PullRequest

#3257 PR for #3232: change Leo's URL in Leo's sources, including xml elements
  leo/commands/commanderHelpCommands.py
  leo/commands/helpCommands.py
  leo/core/leoApp.py
  leo/core/leoAst.py
  leo/core/leoAtFile.py
  leo/core/leoFileCommands.py
  leo/core/leoIPython.py
  leo/core/leoRst.py
  leo/core/leoTips.py
  leo/core/runLeo.py
  leo/plugins/cursesGui2.py
  leo/plugins/free_layout.py
  leo/plugins/mod_leo2ascd.txt
  leo/plugins/qt_gui.py
  leo/unittests/core/test_leoGlobals.py
  setup.py
Labels: Code

#3259 PR for #3258: Remove obsolete comment, but *retain* the dependency!
  setup.py
Labels: Pip, PullRequest

#3262 PR for #3244: g.es_exception
  leo/core/leoGlobals.py
Labels: Bug, PullRequest

#3267 PR for #3266: simplify path handling further
  leo/config/leoSettings.leo
  leo/core/leoCommands.py
  leo/core/leoGlobals.py
  leo/plugins/textnode.py
Labels: Code

#3273 PR: Cleanups of g.os_path wrappers and related methods.
  leo/core/leoCommands.py
  leo/core/leoGlobals.py
Labels: Code, PullRequest

#3279 PR for #3278: crash in g.openUrlHelper
  leo/core/leoGlobals.py
Labels: Bug, PullRequest

#3277 PR for #3276: simplify Leos path functions
  leo/commands/checkerCommands.py
  leo/commands/commanderFileCommands.py
  leo/commands/commanderHelpCommands.py
  leo/commands/convertCommands.py
  leo/commands/debugCommands.py
  leo/commands/editCommands.py
  leo/commands/editFileCommands.py
  leo/commands/spellCommands.py
  leo/core/leoApp.py
  leo/core/leoAtFile.py
  leo/core/leoBridge.py
  leo/core/leoCommands.py
  leo/core/leoConfig.py
  leo/core/leoDebugger.py
  leo/core/leoFileCommands.py
  leo/core/leoGlobals.py
  leo/core/leoImport.py
  leo/core/leoKeys.py
  leo/core/leoMarkup.py
  leo/core/leoRst.py
  leo/core/leoSessions.py
  leo/core/leoShadow.py
  leo/core/leoclient.py
  leo/plugins/bibtex.py
  leo/plugins/contextmenu.py
  leo/plugins/demo.py
  leo/plugins/gitarchive.py
  leo/plugins/graphcanvas.py
  leo/plugins/jinjarender.py
  leo/plugins/leo_to_html.py
  leo/plugins/leomail.py
  leo/plugins/md_docer.py
  leo/plugins/mime.py
  leo/plugins/mod_speedups.py
  leo/plugins/qt_gui.py
  leo/plugins/qt_text.py
  leo/plugins/screen_capture.py
  leo/plugins/screencast.py
  leo/plugins/screenshots.py
  leo/plugins/todo.py
  leo/plugins/viewrendered.py
  leo/plugins/viewrendered3.py
  leo/plugins/xdb_pane.py
  leo/unittests/core/test_leoApp.py
  leo/unittests/core/test_leoAst.py
  leo/unittests/core/test_leoAtFile.py
  leo/unittests/core/test_leoBridge.py
  leo/unittests/core/test_leoCommands.py
  leo/unittests/core/test_leoGlobals.py
  leo/unittests/core/test_leoShadow.py
  leo/unittests/core/test_leoserver.py
  leo/unittests/test_importers.py
  leo/unittests/test_syntax.py
Labels: Code, PullRequest

#3287 PR for #3283: auto-completer crash
  leo/plugins/qt_text.py
Labels: Bug, PullRequest

#3297 PR for #3296: Unnecessary messages in divideAnySplitter
  leo/plugins/nested_splitter.py
  leo/plugins/qt_frame.py
Labels: Bug, PullRequest
