Repository leo-editor/leo-editor, pull requests merged in 2023-03, with the labels that each got.

#3182 PR for #3177: exclude /docs folder folder from pypi distributions
  MANIFEST.in
  leo/dist/leoDist.leo
Labels: Pip, PullRequest

#3183 PR for #3181: Fix crash in g.findUNL
  leo/core/leoGlobals.py
Labels: Bug, PullRequest

#3185 PR: Fix sphinx typos in "what's new"
  leo/doc/LeoDocs.leo
Labels: Documentation

#3191 PR for #3190: crash in show-settings
  leo/core/leoConfig.py
Labels: Bug, PullRequest

#3196 PR for #3194: Add c.find_h/b commands
  leo/core/leoCommands.py
  leo/scripts/test-one-leo.cmd
  leo/unittests/core/test_leoCommands.py
Labels: Enhancement

#3198 leoCommands: execute-external-file command: runs files with ".bash"
  leo/core/leoCommands.py
Labels: Bug

#3204 execute-external-file command: improve terminal detection;
  leo/core/leoCommands.py
Labels: Bug, Enhancement

#3208 PR for #3156: reload settings hook
  leo/core/leoCommands.py
  leo/doc/LeoDocs.leo
Labels: Code

#3209 1. Adjust leo test and utility scripts in the scripts directory to automatically change to the leo-editor directory
  leo/core/LeoPyRef.leo
  leo/scripts/beautify-leo.cmd
  leo/scripts/blacken-leo.cmd
  leo/scripts/flake8-leo.cmd
  leo/scripts/full-test-leo.cmd
  leo/scripts/make-leo.cmd
  leo/scripts/mypy-leo.cmd
  leo/scripts/pylint-leo.cmd
  leo/scripts/reindent-leo.cmd
  leo/scripts/set-repo-dir.cmd
  leo/scripts/test-leo.cmd
  leo/scripts/test-one-leo.cmd
Labels: Enhancement, Code

#3212 PR: revert leo/scripts/reindent-leo.cmd
  leo/scripts/beautify-leo.cmd
  leo/scripts/blacken-leo.cmd
  leo/scripts/flake8-leo.cmd
  leo/scripts/full-test-leo.cmd
  leo/scripts/make-leo.cmd
  leo/scripts/mypy-leo.cmd
  leo/scripts/pylint-leo.cmd
  leo/scripts/reindent-leo.cmd
  leo/scripts/test-leo.cmd
  leo/scripts/test-one-leo.cmd
Labels: Code

#3214 PR: qt_tree.py: expand/contract when mouseover with CTRL/SHIFT
  leo/plugins/qt_tree.py
Labels: Enhancement

#3217 Disable PR #3214. It *might* have caused a hard crash
  leo/plugins/qt_tree.py
Labels: Bug, PullRequest

#3225 PR: Fix crash in autosave
  leo/plugins/leoflexx.py
  leo/plugins/mod_autosave.py
Labels: Bug

#3227 PR for #3121: headline numbers
  leo/commands/editCommands.py
Labels: Enhancement
