Repository leo-editor/leo-editor, pull requests merged in 2023-06, with the labels that each got.

#3362 PR for #3358: improve c++ importer
  leo/plugins/importers/c.py
  leo/unittests/test_importers.py
Labels: Enhancement, PullRequest

#3367 PR: Import Callable from collections.abc insead of typing
  leo/commands/abbrevCommands.py
  leo/commands/bufferCommands.py
  leo/commands/commanderOutlineCommands.py
  leo/commands/controlCommands.py
  leo/commands/convertCommands.py
  leo/commands/debugCommands.py
  leo/commands/editCommands.py
  leo/commands/editFileCommands.py
  leo/commands/helpCommands.py
  leo/commands/killBufferCommands.py
  leo/commands/rectangleCommands.py
  leo/commands/spellCommands.py
  leo/core/leoApp.py
  leo/core/leoAst.py
  leo/core/leoAtFile.py
  leo/core/leoBackground.py
  leo/core/leoChapters.py
  leo/core/leoColorizer.py
  leo/core/leoCommands.py
  leo/core/leoExternalFiles.py
  leo/core/leoFileCommands.py
  leo/core/leoFind.py
  leo/core/leoFrame.py
  leo/core/leoGlobals.py
  leo/core/leoGui.py
  leo/core/leoImport.py
  leo/core/leoKeys.py
  leo/core/leoMenu.py
  leo/core/leoNodes.py
  leo/core/leoPlugins.py
  leo/core/leoPrinting.py
  leo/core/leoRst.py
  leo/core/leoUndo.py
  leo/core/leoVim.py
  leo/core/leoserver.py
  leo/core/signal_manager.py
  leo/plugins/contextmenu.py
  leo/plugins/cursesGui.py
  leo/plugins/cursesGui2.py
  leo/plugins/mod_scripting.py
  leo/plugins/nodetags.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_gui.py
  leo/plugins/qt_text.py
  leo/plugins/qt_tree.py
  leo/plugins/quicksearch.py
  leo/plugins/todo.py
  leo/plugins/viewrendered.py
  leo/plugins/writers/org.py
  leo/unittests/core/test_leoAst.py
Labels: Code, PullRequest

#3372 PR: Fix two comments and simplify g.isValidLanguage
  leo/core/leoApp.py
  leo/core/leoAtFile.py
  leo/core/leoGlobals.py
Labels: Code

#3371 Themes: quote @font-family fall-back fonts that have multi-word names in tbp_xxx themes
  leo/themes/minimal-ui-tbp_dark_solarized.leo
  leo/themes/minimal-ui-tbp_light_quasi-solarized.leo
  leo/themes/minimal-ui-tbp_light_solarized.leo
  leo/themes/tbp_dark.leo
  leo/themes/tbp_dark_solarized.leo
  leo/themes/tbp_light.leo
  leo/themes/tbp_light_solarized.leo
Labels: Bug, lvl:minor

#3377 PR: Improve annotations of leoAst.py
  leo/core/leoAst.py
Labels: Code

#3376 PR for #3375: improve python importer
  leo/plugins/importers/base_importer.py
  leo/plugins/importers/ini.py
  leo/plugins/importers/leo_rst.py
  leo/plugins/importers/lua.py
  leo/plugins/importers/otl.py
  leo/plugins/importers/python.py
  leo/plugins/importers/treepad.py
  leo/scripts/reindent-leo.cmd
  leo/unittests/core/test_leoImport.py
  leo/unittests/test_importers.py
Labels: Enhancement, PullRequest

#3379 PR: put @path in body text. Use path: in headlines
  leo/core/leoImport.py
  leo/unittests/core/test_leoImport.py
Labels: Code, PullRequest

#3380 PR for #3359: git-diff
  leo/commands/editFileCommands.py
Labels: Bug, PullRequest

#3382 PR for #3381: rewrite LM.scanOptions w/o argparse
  leo/core/leoApp.py
Labels: PullRequest

#3384 PR: add timeout kwarg to requests.get
  leo/core/leoGlobals.py
  leo/core/leoTips.py
Labels: Code, PullRequest

#3388 PR for #3386: option checks
  leo/core/leoApp.py
Labels: Code, PullRequest

#3392 PR: fix various problems with rpcalc plugin
  leo/plugins/rpcalc.py
Labels: Code, PullRequest

#3399 PR for #3312: diff-leo-files
  leo/unittests/core/test_leoAst.py
  leo/unittests/core/test_leoImport.py
Labels: Bug, PullRequest
