Repository leo-editor/leo-editor, pull requests merged in 2024-07, with the labels that each got.

#3989 Fix 'late quirp' in leoUndo.py
  leo/core/leoUndo.py
Labels: Bug, lvl:minor

#3995 PR for 6.8.0-1
  MANIFEST.in
  leo/scripts/install_leo_locally.py
  pyproject.toml
  requirements.txt
Labels: Pip

#3997 PR for #3996: Update distribution checklist
  leo/dist/leoDist.leo
Labels: Documentation

#4000 PR for #3998: use script to sync requirements files.
  pyproject.toml
  requirements.txt
Labels: Code

#3999 PR for #3988: crash in pygments colorizer
  leo/core/leoColorizer.py
  leo/core/leoCommands.py
  leo/unittests/core/test_leoColorizer.py
Labels: Bug, leoJS

#4003 PR for #3986: set-ui status bits
  leo/commands/editCommands.py
Labels: lvl:minor, Code

#4005 PR for #3990: uAs on @edit nodes
  leo/core/leoFileCommands.py
Labels: Bug, leoJS

#4008 PR for #4006: url's in CheatSheet.leo
  leo/doc/CheatSheet.leo
  leo/plugins/pyplot_backend.py
  leo/plugins/viewrendered.py
Labels: Bug, Documentation

#4014 PR for #4009: crash in VR plugin
  leo/plugins/viewrendered.py
  leo/plugins/viewrendered3.py
  pyproject.toml
  requirements.txt
Labels: Bug

#3984 Make Images Display Correctly For rest, md, and asciidoc
  leo/plugins/viewrendered3.py
Labels: Code

#4019 PR for #3876: drag & drop
  leo/plugins/qt_frame.py
Labels: Bug

#3903 Correcting stickynotes.py
  leo/plugins/stickynotes.py
Labels: Bug

#4020 PR for #4012: dialog does not return proper values.
  leo/plugins/cursesGui.py
  leo/plugins/qt_gui.py
Labels: Bug

#4023 VR3 - Fix Clipboard Trashing
  leo/plugins/viewrendered3.py
Labels: Bug

#4022 PR for #4015: enable extract menus
  leo/core/leoCommands.py
Labels: lvl:minor, UX, Anomaly

#4025 PR for #3586: rclick docs
  leo/config/leoSettings.leo
Labels: Documentation

#4024 PR for #3894: crash in editpane plugin
  leo/plugins/editpane/csvedit.py
  leo/plugins/editpane/editpane.py
  leo/plugins/editpane/leotextedit.py
  leo/plugins/editpane/plaintextedit.py
  leo/plugins/editpane/vanillascintilla.py
Labels: Bug
