Repository leo-editor/leo-editor, pull requests merged in 2024-10, with the labels that each got.

#4075 Quicksearch: Remove the go-anywhere command. Correct, update, and re-wrap the docstring.
  leo/plugins/quicksearch.py
Labels: Bug, Enhancement, Documentation

#4079 PR for #4078: fix errors in PR #4077
  leo/plugins/qt_layout.py
  leo/plugins/viewrendered3.py
  leo/unittests/plugins/test_plugins.py
Labels: Bug

#4081 PR for #4066
  leo/core/leoChapters.py
Labels: Bug

#4086 PR for #4083: Add layout diagrams to two docstrings
  leo/plugins/qt_layout.py
Labels: Documentation

#4088 PR for #4087: Remove all `allowBinding` and `shortcut` kwargs from calls to `k.registerCommand`
  leo/core/leoChapters.py
  leo/core/leoKeys.py
  leo/core/leoPlugins.py
  leo/plugins/mod_scripting.py
  leo/plugins/quicksearch.py
Labels: Bug, Code

#4089 Correct show_vr_pane() and its name
  leo/plugins/qt_layout.py
Labels: Bug, UX

#4092 PR for #4090: undo mistakes in PR #4088
  leo/core/leoKeys.py
  leo/plugins/mod_scripting.py
Labels: Bug

#4094 PR: allow lower-case f-keys in @key bindings
  leo/core/leoKeys.py
  leo/plugins/mod_scripting.py
Labels: Bug

#4100 execute-external-file Command: Fix and Enhance
  leo/core/leoCommands.py
Labels: Bug, Enhancement

#4115 PR: Tweaks re removing leoIPython.py
  leo/core/leoApp.py
  leo/doc/LeoDocs.leo
  leo/plugins/qt_gui.py
  leo/unittests/core/test_leoApp.py
Labels: Documentation, Code

#4114 PR for #4112: Retire two plugins and one related file
  leo/core/LeoPyRef.leo
  leo/doc/LeoDocs.leo
  leo/external/stringlist.py
  leo/plugins/jinjarender.py
  leo/plugins/valuespace.py
Labels: Code

#4111 Use new layouts at startup
  leo/core/leo_rst_html.html
  leo/plugins/qt_frame.py
  leo/plugins/qt_layout.py
  leo/plugins/viewrendered.py
Labels: Enhancement

#4120 PR: Fix PR #4111: don't enable VR3 automatically
  leo/plugins/qt_frame.py
  leo/plugins/qt_layout.py
Labels: Bug

#4121 Finalize New Layouts; Add help-for-layouts and layout-show-layouts Commands
  leo/commands/helpCommands.py
  leo/config/leoSettings.leo
  leo/plugins/qt_layout.py
Labels: Enhancement, UX

#4129 Fix the help-for-layouts command
  leo/commands/helpCommands.py
  leo/plugins/qt_layout.py
Labels: Bug

#4133 PR for #4104: g.cls should work on Linux
  leo/core/leoGlobals.py
Labels: Enhancement

#4134 PR for #4130: fix a docstring
  leo/plugins/qt_layout.py
Labels: Bug, lvl:minor

#4136 PR for #4123: Fix all expand/contract-*-pane commands
  leo/plugins/qt_frame.py
  leo/plugins/qt_gui.py
  leo/plugins/qt_layout.py
  leo/plugins/viewrendered3.py
Labels: Bug

#4138 PR for #4137: Automatically create @jupytext children
  leo/config/leoSettings.leo
  leo/core/LeoPyRef.leo
  leo/core/leoAtFile.py
  leo/core/leoJupytext.py
  leo/doc/leoAttic.txt
  leo/unittests/core/test_leoAtFile.py
  leo/unittests/plugins/test_importers.py
Labels: Enhancement
