Repository leo-editor/leo-editor, pull requests merged in 2024-05, with the labels that each got.

#3902 PR for #3901: Add toggle-unl-view
  leo/core/leoFrame.py
  leo/plugins/qt_frame.py
Labels: Enhancement

#3906 PR for #3905: ratio properties
  leo/commands/commanderFileCommands.py
  leo/core/leoConfig.py
  leo/core/leoFileCommands.py
  leo/core/leoFrame.py
  leo/core/leoGlobals.py
  leo/doc/leoAttic.txt
  leo/plugins/cursesGui.py
  leo/plugins/cursesGui2.py
  leo/plugins/demo.py
  leo/plugins/leoOPML.py
  leo/plugins/qt_frame.py
Labels: Bug, Code

#3914 Fix erroneous command if pyenchant library isn't present.
  leo/commands/spellCommands.py
Labels: Bug

#3921 PR for #3920: show-qt-widgets
  leo/plugins/qt_frame.py
Labels: Enhancement

#3922 PR for #3916: Improve `restart-leo` command
  leo/commands/commanderFileCommands.py
  leo/core/leoApp.py
Labels: Enhancement

#3929 PR 2 for #3915
  leo/core/leoApp.py
  leo/core/leoCommands.py
  leo/core/leoFind.py
  leo/core/leoserver.py
  leo/plugins/leoflexx.py
  leo/plugins/qt_gui.py
  leo/unittests/core/test_leoserver.py
Labels: Code

#3897 FreeWin Fixes - Better Display Of Local Images
  leo/plugins/freewin.py
Labels: Bug

#3927 VR3: Prevent exception on first toggle.
  leo/plugins/viewrendered3.py
Labels: Bug

#3872 PR for #3871: searching for definitions should not change search settings
  leo/config/leoSettings.leo
  leo/core/leoCommands.py
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/plugins/quicksearch.py
  leo/unittests/core/test_leoFind.py
Labels: Enhancement, leoInteg, leoJS

#3940 PR for #3939: Suppress a FutureWarning in Leo's colorizer
  leo/core/leoColorizer.py
Labels: Code

#3936 PR for #3935: fix server.is_valid
  leo/core/leoserver.py
Labels: Bug

#3937 PR for #3934: undo for clone-to-at-spot
  leo/commands/commanderOutlineCommands.py
Labels: Bug

#3943 Fixes leoserver.py to support the new "find-def" with the nav pane quicksearch controller. Fixes #3942
  leo/core/leoserver.py
Labels: Code

#3945 PR for #3944: A failing unit test in the server
  leo/core/leoFind.py
  leo/core/leoserver.py
Labels: Bug

#3947 PR for #3946: optional Qt modules
  leo/core/leoQt.py
  leo/core/runLeo.py
  leo/plugins/backlink.py
  leo/plugins/graphcanvas.py
  leo/plugins/todo.py
Labels: Pip

#3951 PR for #3949: crash in vr
  leo/plugins/qt_gui.py
  leo/plugins/viewrendered.py
Labels: Bug

#3958 PR for #3957: leoAtFile blunder
  leo/core/leoAtFile.py
Labels: Bug, Code
