Repository leo-editor/leo-editor, pull requests merged in 2024-02, with the labels that each got.

#3785 PR Update LeoPyRef.leo
  leo/core/LeoPyRef.leo
Labels: Pip

#3786 PR: Tweaks to Nim coloring
  leo/modes/nim.py
Labels: Enhancement

#3787 PR: clean modes/python.py
  leo/config/leoSettings.leo
Labels: Enhancement, Code

#3795 PR: More tweaks to leoTokens.py
  leo/core/leoTokens.py
Labels: Enhancement

#3790 Added support for a 'get UNL' command to the leo server.
  leo/core/leoserver.py
Labels: Enhancement, leoJS

#3797 Fix leo server bugs with 'get unl' and other 'hasattr' misuses,
  leo/core/leoserver.py
Labels: Enhancement

#3784 PR: Improve various docstrings
  leo/commands/helpCommands.py
Labels: Documentation, Code

#3802 PR for #3749: crash in wikiview plugin
  leo/plugins/qt_text.py
  leo/plugins/wikiview.py
Labels: Bug

#3804 PR: workaround for #3744: autocomplete/calltips fails
  leo/core/leoKeys.py
Labels: Bug

#3805 PR 2 for #3743
  leo/core/leoKeys.py
Labels: Bug

#3806 PR for #3800: goto prev/back
  leo/commands/commanderOutlineCommands.py
  leo/core/leoHistory.py
Labels: Bug, leoJS

#3801 PR for #3759: '\r' in pasted text
  leo/core/leoFrame.py
Labels: Bug, WaitingForReview

#3742 Fix incorrect Window title in some edge cases.
  leo/plugins/qt_frame.py
Labels: Bug, lvl:minor

#3807 PR for #3803: Problems with python importer
  leo/plugins/importers/python.py
  leo/unittests/plugins/test_importers.py
Labels: Bug

#3812 PR for #3811: handle short unls
  leo/core/leoGlobals.py
  leo/test/test.leo
  leo/unittests/core/test_leoGlobals.py
Labels: Bug, WaitingForReview

#3815 PR for #3814: Better defaults for UNLs with short file names
  leo/core/leoGlobals.py
  leo/doc/leoAttic.txt
  leo/test/test.leo
  leo/unittests/core/test_leoGlobals.py
Labels: Enhancement

#3819 PR for #3818
  leo/core/leoTokens.py
Labels: Bug

#3817 PR for #3816: improved UNLs
  leo/core/leoGlobals.py
  leo/test/test.leo
Labels: Enhancement, WaitingForReview, leoJS

#3775 PR for #3767: easy install from GitHub
  MANIFEST.in
  leo/core/leoApp.py
  leo/core/leoGlobals.py
  leo/core/leoImport.py
  leo/dist/leoDist.leo
  leo/modes/ini.py
  leo/plugins/importers/c.py
  leo/plugins/leo_babel/babel_lib.py
  leo/plugins/todo.py
  leo/scripts/pip-install-r.cmd
  leo/scripts/pip-uninstall-all.cmd
  new-requirements.txt
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
Labels: Pip
