Repository leo-editor/leo-editor, pull requests merged in 2024-03, with the labels that each got.

#3827 Boltex/issue3826
  leo/core/leoFileCommands.py
  leo/core/leoserver.py
Labels: Enhancement

#3830 PR for #3829: Retire runAskLeoIDDialog
  leo/core/leoGui.py
  leo/doc/leoAttic.txt
  leo/plugins/cursesGui2.py
  leo/plugins/qt_gui.py
  leo/unittests/plugins/test_gui.py
Labels: Code

#3831 PR for #3335: create myLeoSettings.leo
  leo/commands/commanderHelpCommands.py
  leo/core/leoCache.py
Labels: Bug, Enhancement

#3835 PR3 for Leo 6.7.8
  MANIFEST.in
  PKG-INFO.TXT
  leo/core/leoVersion.py
  leo/dist/leoDist.leo
  pyproject.toml
Labels: Pip

#3841 Add g.traceUnique and g.traceUniqueClass
  leo/core/leoGlobals.py
Labels: Enhancement

#3842 Suppress pyflakes complaints
  leo/plugins/qt_tree.py
Labels: Code

#3844 PR: Add g.isUniqueClass
  leo/core/leoGlobals.py
Labels: Enhancement

#3848 PR for #3843: serious bug in leoAst.py
  leo/core/leoAst.py
Labels: Bug
