Repository leo-editor/leo-editor, pull requests merged in 2024-11, with the labels that each got.

#4140 PR for #4139: leo/modes/jupytext.py
  leo/core/leoApp.py
  leo/core/leoColorizer.py
  leo/core/leoJupytext.py
  leo/modes/jupytext.py
  leo/unittests/plugins/test_importers.py
Labels: Enhancement

#4142 Jkn 4141 declutter
  leo/plugins/qt_tree.py
Labels: Bug

#4135 PR for #4132: document @jupytext
  leo/doc/LeoDocs.leo
Labels: Documentation

#4163 PR 2 for #4160: fix a path in pylint.get_rc_file
  leo/commands/checkerCommands.py
Labels: Bug

#4147 PR for #4146: Improve the jedit colorizer
  leo/commands/commanderEditCommands.py
  leo/commands/rectangleCommands.py
  leo/core/LeoPyRef.leo
  leo/core/leoColorizer.py
  leo/core/leoCommands.py
  leo/core/leoConfig.py
  leo/core/leoFrame.py
  leo/core/leoGlobals.py
  leo/core/leoJupytext.py
  leo/core/leoUndo.py
  leo/doc/IpythonBridge.txt
  leo/doc/LeoDocs.leo
  leo/doc/colorizer.md
  leo/modes/jupytext.py
  leo/modes/md.py
  leo/modes/python.py
  leo/plugins/qt_tree.py
  leo/unittests/core/test_leoColorizer.py
Labels: Bug

#4167 PR for #4159: don't change outline when auto-beautifying Python files
  leo/core/leoAtFile.py
  leo/core/leoTokens.py
Labels: Bug

#4168 PR: Fix a crash when using pygments colorer
  leo/core/leoColorizer.py
Labels: Bug

#4165 PR for #4164: Disable the 'no popup' popup
  leo/plugins/qt_gui.py
Labels: Bug

#4169 PR for #4156: two unit tests fail for Python 3.13
  leo/external/npyscreen/__init__.py
  leo/unittests/core/test_leoAst.py
  leo/unittests/core/test_leoTokens.py
  leo/unittests/plugins/test_plugins.py
Labels: Bug, Testing

#4172 PR for #4171: speed up @killcolor
  leo/core/leoColorizer.py
Labels: Enhancement

#4173 PR 2 for #4171: @killcolor
  leo/core/leoColorizer.py
Labels: Bug

#4178 PR #2 for openSCAD.
  leo/core/leoApp.py
  leo/modes/openscad.py
  leo/scripts/leoScripts.txt
  leo/scripts/scripts.leo
Labels: Code

#4174 PR for #4166: Rewrite the syntax chapter
  docs/_sources/coloring.html.txt.txt
  docs/appendices.html
  docs/coloring.html
  docs/customizing.html
  docs/genindex.html
  docs/intermediatetopics.html
  docs/leo_toc.html
  docs/objects.inv
  docs/search.html
  docs/searchindex.js
  docs/slides/_sources/coloring.txt
  docs/slides/coloring.html
  docs/usersguide.html
  leo/core/leoColorizer.py
  leo/doc/LeoDocs.leo
  leo/doc/_sources/coloring.html.txt.txt
  leo/doc/html/conf.py
Labels: Documentation

#4182 PR for #4181: severe colorizer bug
  leo/core/leoColorizer.py
  leo/core/leoFrame.py
  leo/doc/LeoDocs.leo
Labels: Bug, ReleaseBlocker

#4180 Freewin - Use Host's Text, Background Colors For Rendered View
  leo/plugins/freewin.py
Labels: Enhancement, UX

#4176 VR3 - Match Body Editor Colors, Make Sure VR3 Won't Render While Invisible
  leo/plugins/viewrendered3.py
  leo/plugins/viewrendered3/vr3-medium-black.css
Labels: Enhancement

#4188 PR for #4187: More tweaks to the jedit class
  leo/core/leoColorizer.py
  leo/plugins/patch_python_colorizer.py
  leo/unittests/core/test_leoColorizer.py
Labels: Code

#4185 Freewin: Remove unneeded diagnostic log message.
  leo/plugins/freewin.py
Labels: Bug

#4190 PR Require kwargs for most pattern matchers
  leo/core/leoColorizer.py
  leo/modes/clojure.py
  leo/modes/html.py
  leo/modes/javascript.py
  leo/modes/nim.py
  leo/scripts/scripts.leo
  leo/unittests/misc_tests/test_syntax.py
Labels: Code

#4195 PR: Remove jedit kwargs
  leo/core/leoColorizer.py
  leo/unittests/misc_tests/test_syntax.py
Labels: Code

#4198 PR for #3967: colorize GLSL
  leo/core/leoApp.py
Labels: Enhancement

#4202 PR: Refactor mode files
  leo/modes/css.py
  leo/modes/html.py
  leo/modes/javascript.py
  leo/modes/vue.py
Labels: Code

#4205 VR3 - Restore Scroll Position After Updates
  leo/plugins/viewrendered3.py
Labels: Enhancement

#4209 PR for #4208: improve @button make-sphinx in LeoDocs.leo
  docs/index.html
  leo/doc/LeoDocs.leo
  leo/doc/leoAttic.txt
  leo/scripts/sphinx_build.py
Labels: Enhancement, Documentation, Pip, Code

#4218 PR for #4175: writing in the log pane
  leo/plugins/qt_frame.py
Labels: Bug

#4216 PR for #4211: update tips
  leo/core/leoTips.py
Labels: Documentation, Tip

#4219 PR for #4116: python importer bug
  leo/core/leoApp.py
  leo/plugins/importers/python.py
  leo/unittests/plugins/test_importers.py
Labels: Bug

#4221 PR for #4220: Remove dw.change_layout
  leo/doc/leoAttic.txt
  leo/plugins/qt_frame.py
Labels: Code

#4228 Fix recent blunder in PR #4223
  leo/plugins/qt_tree.py
Labels: Bug, ReleaseBlocker
