Repository leo-editor/leo-editor, pull requests merged in 2024-09, with the labels that each got.

#4060 VR3 - Fix Plugin Menu <module>/about Message Not Displaying The First Time
  leo/plugins/viewrendered3.py
Labels: Bug

#4061 PR: fix quirps reported by Félix
  leo/doc/LeoDocs.leo
  leo/plugins/trace_tags.py
Labels: Documentation

#4064 PR for #4063: pylint complaints
  leo/commands/checkerCommands.py
  leo/commands/commanderEditCommands.py
  leo/commands/convertCommands.py
  leo/commands/spellCommands.py
  leo/core/leoApp.py
  leo/core/leoAst.py
  leo/core/leoAtFile.py
  leo/core/leoColorizer.py
  leo/core/leoCommands.py
  leo/core/leoCompare.py
  leo/core/leoConfig.py
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/core/leoQt.py
  leo/core/leoTest2.py
  leo/core/leoTokens.py
  leo/core/leoUndo.py
  leo/core/leoVim.py
  leo/core/leoserver.py
  leo/core/runLeo.py
  leo/doc/LeoDocs.leo
  leo/doc/leoAttic.txt
  leo/plugins/attrib_edit.py
  leo/plugins/cursesGui2.py
  leo/plugins/demo.py
  leo/plugins/editpane/csvedit.py
  leo/plugins/freewin.py
  leo/plugins/importers/rust.py
  leo/plugins/leo_babel/tests/idle_time.py
  leo/plugins/leo_cloud.py
  leo/plugins/leoflexx.py
  leo/plugins/mod_http.py
  leo/plugins/mod_scripting.py
  leo/plugins/nodediff.py
  leo/plugins/pyplot_backend.py
  leo/plugins/qt_events.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_gui.py
  leo/plugins/qt_tree.py
  leo/plugins/richtext.py
  leo/plugins/rpcalc.py
  leo/plugins/screenshots.py
  leo/plugins/sftp.py
  leo/plugins/stickynotes_plus.py
  leo/plugins/todo.py
  leo/plugins/viewrendered.py
  leo/plugins/viewrendered3.py
  leo/scripts/pylint_leo.py
  leo/scripts/remove_duplicate_pictures.py
  leo/test/pylint-leo-rc-ref.txt
Labels: Code

#4068 PR for #4067: run-pylint-on-write
  leo/commands/checkerCommands.py
  leo/config/leoSettings.leo
  leo/core/leoAtFile.py
Labels: Enhancement

#4062 Fix vr3-toggle and vr3-show commands
  leo/plugins/viewrendered3.py
Labels: Bug

#4074 PR: Remove weird pylint default
  leo/commands/checkerCommands.py
Labels: Code
