Repository leo-editor/leo-editor, pull requests merged in 2024-08, with the labels that each got.

#4027 Tbp vr3 refactor and cleanup, reduce technical debt
  leo/plugins/viewrendered3.py
Labels: Bug, Enhancement, Refactor/Technical Debt

#4034 Fix three unit tests so they handle unicode properly
  leo/unittests/plugins/test_plugins.py
Labels: Bug

#4035 PR for #4028: fix VR flash.
  leo/plugins/viewrendered.py
Labels: Bug

#4036 PR for #4031: find crash
  leo/core/leoFind.py
Labels: Bug

#4039 Freewin Plugin: Automatic Matching Of Theme Colors, Line Highlighting
  leo/plugins/freewin.py
Labels: Enhancement

#4045 PR Move destroyAllObjects to the attic
  leo/doc/leoAttic.txt
  leo/plugins/qt_frame.py
Labels: Code

#4047 PR for #4046: remove add-editor command
  leo/config/leoSettings.leo
  leo/core/leoChapters.py
  leo/core/leoFrame.py
  leo/core/leoUndo.py
  leo/doc/LeoDocs.leo
  leo/doc/leoAttic.txt
  leo/plugins/cursesGui2.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_text.py
Labels: Bug, Enhancement, Code

#4044 PR: Add FAQ re install PyQt6-WebEngine on Linux
  leo/doc/LeoDocs.leo
Labels: Documentation

#4051 PR for #4041: loadOnePlugin
  leo/core/leoPlugins.py
Labels: Bug

#4055 PR for #4054: dw.change_layout adds nodes as needed
  leo/plugins/qt_frame.py
Labels: Enhancement

#4058 PR for #4056: Retire reload-outline.
  leo/doc/leoAttic.txt
  leo/plugins/qt_frame.py
Labels: Bug

#4043 VR3 - Simplify Code For Split Layouts; Change Default Layout
  leo/plugins/viewrendered3.py
Labels: Bug, Enhancement
