Repository leo-editor/leo-editor, pull requests merged in 2024-12, with the labels that each got.

#4234 PR for #4233: Remove 'meta' from both requirements files
  pyproject.toml
  requirements.txt
Labels: Pip

#4238 PR for #4236: fix example in quickstart.leo
  leo/doc/quickstart.leo
Labels: Documentation

#4242 PR for #4235: Fix broken links
  docs/FAQ.html
  docs/acknowledgements.html
  docs/appendices.html
  docs/cheatsheet.html
  docs/clickablelinks.html
  docs/commands.html
  docs/console-gui.html
  docs/customizing.html
  docs/debuggers.html
  docs/directives.html
  docs/emacs.html
  docs/getting-started.html
  docs/glossary.html
  docs/history.html
  docs/index.html
  docs/installing.html
  docs/intermediatetopics.html
  docs/jupyternotebooks.html
  docs/leo-university.html
  docs/leoBridge.html
  docs/leoLinks.html
  docs/leo_toc.html
  docs/leoandasciidoc.html
  docs/leoandotherprograms.html
  docs/leomarkup.html
  docs/leonine-world.html
  docs/leoserver.html
  docs/license.html
  docs/plugins.html
  docs/preface.html
  docs/preliminaries.html
  docs/running.html
  docs/screen-shots.html
  docs/screencasts.html
  docs/scripting-miscellany.html
  docs/search.html
  docs/searchindex.js
  docs/slides.html
  docs/testimonials.html
  docs/theory.html
  docs/toc-more-links.html
  docs/tutorial-basics.html
  docs/tutorial-pim.html
  docs/tutorial-rst3.html
  docs/tutorial-scripting.html
  docs/tutorial-tips.html
  docs/tutorial.html
  docs/usersguide.html
  docs/vim-theory.html
  docs/vimBindings.html
  docs/what-is-new.html
  docs/writingPlugins.html
  leo/doc/LeoDocs.leo
  leo/doc/html/leo_toc.html.txt
  leo/doc/importers.md
Labels: Documentation

#4244 PR for #4243: focus glitch
  leo/core/leoApp.py
  leo/core/leoCommands.py
Labels: Bug

#4252 PR: add show-buttons-and-at-commands command
  leo/core/leoKeys.py
  leo/doc/leoAttic.txt
Labels: Enhancement

#4254 VR3 - fix unfreeze when reloaded
  leo/plugins/viewrendered3.py
Labels: Bug
