Repository leo-editor/leo-editor, pull requests merged in 2024-01, with the labels that each got.

#3737 PR for #3736: old-style unls do not work
  leo/core/leoGlobals.py
  leo/test/test.leo
  leo/unittests/core/test_leoGlobals.py
Labels: Bug, WaitingForReview

#3748 PR for #3746 and #3747: annotations for LeoPluginsController
  leo/core/leoApp.py
  leo/core/leoPlugins.py
Labels: Code, WaitingForReview

#3752 PR for #3751: split Token classes in leoAst.py
  leo/core/leoAst.py
Labels: Code

#3762 PR for #3758: Revise discussion of events, especially hyper* events.
  docs/index.html
  leo/doc/LeoDocs.leo
  leo/doc/demo.md
  leo/doc/importers.md
Labels: Documentation

#3761 Boltex/issue3760
  docs/_sources/acknowledgements.html.txt.txt
  docs/acknowledgements.html
  leo/core/LeoPyRef.leo
  leo/core/leoApp.py
  leo/core/leoBridge.py
  leo/core/leoserver.py
  leo/doc/LeoDocs.leo
  leo/doc/_sources/acknowledgements.html.txt.txt
  leo/plugins/mod_scripting.py
  leo/unittests/core/test_leoserver.py
Labels: Enhancement, leoInteg

#3771 PR for #3770: Revert colorizing for f-strings
  leo/modes/python.py
Labels: Enhancement

#3757 PR3 for #3744: token-based beautifier
  leo/commands/commanderEditCommands.py
  leo/commands/convertCommands.py
  leo/commands/editFileCommands.py
  leo/core/leoApp.py
  leo/core/leoAst.py
  leo/core/leoAtFile.py
  leo/core/leoBeautify.py
  leo/core/leoCache.py
  leo/core/leoColorizer.py
  leo/core/leoCommands.py
  leo/core/leoFind.py
  leo/core/leoGlobals.py
  leo/core/leoTokens.py
  leo/core/leoUndo.py
  leo/doc/leoAttic.txt
  leo/plugins/importers/markdown.py
  leo/plugins/writers/markdown.py
  leo/scripts/full-test-leo.cmd
  leo/scripts/tbo.cmd
  leo/unittests/commands/test_gotoCommands.py
  leo/unittests/commands/test_spellCommands.py
  leo/unittests/core/test_leoAst.py
  leo/unittests/core/test_leoAtFile.py
  leo/unittests/core/test_leoColorizer.py
  leo/unittests/core/test_leoGlobals.py
  leo/unittests/core/test_leoTokens.py
  leo/unittests/test_importers.py
  leo/unittests/test_writers.py
Labels: Enhancement, Code, leoJS, Nim
