Repository leo-editor/leo-editor, pull requests merged in 2024-04, with the labels that each got.

#3858 Improve annotations in leoCommands.py
  leo/core/leoCommands.py
Labels: Code

#3860 Remove all 'Any' annotations from leoChapters.py
  leo/core/leoChapters.py
Labels: Code

#3861 Annotate leo/core/leoFileCommands.py
  leo/core/leoFileCommands.py
Labels: Code

#3862 PR: Remove all 'Any' and 'Union' annotations from leoBackground.py
  leo/core/leoBackground.py
Labels: Code

#3863 PR: annotate leoAtFile
  leo/core/leoAtFile.py
  leo/unittests/core/test_leoAtFile.py
Labels: Code

#3865 PR: more annotations for leoFileCommands.py
  leo/core/leoFileCommands.py
Labels: Code

#3867 PR: Fix bug in python-to-rust
  leo/commands/convertCommands.py
Labels: Bug

#3868 VR3: Improved handling of file: paths in @jupyter nodes.
  leo/plugins/viewrendered3.py
Labels: Code

#3882 PR for #3823: import-any-file
  leo/core/leoImport.py
Labels: Bug, WaitingForReview

#3878 PR for #3809: recolor body text when moving nodes
  leo/commands/commanderOutlineCommands.py
  leo/core/leoColorizer.py
  leo/core/leoCommands.py
  leo/core/leoFrame.py
Labels: Bug, WaitingForReview

#3880 PR for #3337: edit settings
  leo/commands/commanderHelpCommands.py
Labels: Bug, WaitingForReview

#3883 PR for #3720: Add links to LeoInteg and LeoJS
  leo/doc/LeoDocs.leo
Labels: Documentation

#3885 PR for #3884: TypeAlias does not exist before Python 3.12
  leo/core/leoVim.py
  leo/plugins/qt_frame.py
  leo/plugins/qt_gui.py
  leo/plugins/qt_text.py
  leo/plugins/quicksearch.py
Labels: Bug

#3879 PR for #3141: restart command crashes
  leo/commands/commanderFileCommands.py
  leo/core/leoExternalFiles.py
Labels: Bug, WaitingForReview

#3808 Leo babel 2
  leo/plugins/leo_babel/babel.py
  leo/plugins/leo_babel/babel_api.py
  leo/plugins/leo_babel/babel_lib.py
  leo/plugins/leo_babel/code.leo
  leo/plugins/leo_babel/doc.leo
  leo/plugins/leo_babel/doc/Leo-Babel.html
  leo/plugins/leo_babel/doc/Leo-Babel.md
  leo/plugins/leo_babel/doc/Leo-Babel.pdf
  leo/plugins/leo_babel/doc/Leo-Babel.rst
  leo/plugins/leo_babel/doc/doc.txt
  leo/plugins/leo_babel/doc/maintenance.html
  leo/plugins/leo_babel/doc/maintenance.md
  leo/plugins/leo_babel/doc/maintenance.pdf
Labels: Code

#3886 PR: restart-leo should not call sys.exit after Popen.run
  leo/commands/commanderFileCommands.py
Labels: Code, WaitingForReview

#3891 Make URLs relative to the current directory work so, e.g., images in …
  leo/plugins/freewin.py
Labels: Bug
