Repository leo-editor/leo-editor, pull requests merged in 2025-08, with the labels that each got.

#4421 PR fixes #4420: Fix beautifier bugs
  leo/core/leoAst.py
  leo/core/leoTokens.py
  leo/core/leoUndo.py
  leo/plugins/leoscreen.py
  leo/plugins/mod_scripting.py
  leo/plugins/rpcalc.py
  leo/unittests/core/test_leoTokens.py
  leo/unittests/plugins/test_importers.py
Labels: Bug

#4430 PR fixes #4398: coloring docstrings fails after cutting/pasting text
  leo/core/leoFrame.py
Labels: Bug

#4429 feat(themes): Change SwotMoknokai font-size and right click menu seleted text color
  leo/themes/SwotMoknokai.leo
Labels: Enhancement

#4437 Fix several quirps in Leo's unit tests
  leo/unittests/plugins/test_importers.py
Labels: Code
