Repository leo-editor/leo-editor, pull requests merged in 2025-01, with the labels that each got.

#4257 PR for #4256: but in at.scanAllDirectives
  leo/core/leoAtFile.py
Labels: Bug

#4263 Make Built-in Layouts Have Slots For Both VR and VR3
  leo/plugins/qt_layout.py
  leo/plugins/viewrendered3.py
Labels: Enhancement

#4258 VR3 - Fix RsT image, figure directives for relative image paths.
  leo/plugins/viewrendered3.py
Labels: Bug

#4265 PR: Retain modification time when executing scripts
  leo/core/leoCommands.py
Labels: Enhancement

#4264 PR: Improve VR imports
  leo/plugins/viewrendered.py
Labels: Bug

#4267 PR for #4260: @pdf paths
  leo/plugins/viewrendered.py
Labels: Enhancement

#4269 PR: Fix blunders in rust.py and python.py
  leo/modes/python.py
  leo/modes/rust.py
Labels: Bug

#4274 PR for #4271: unit test for modes
  leo/unittests/misc_tests/test_modes.py
  leo/unittests/misc_tests/test_syntax.py
Labels: Testing

#4280 PR for #4276: requirements for windows-curses package
  pyproject.toml
  requirements.txt
Labels: Pip

#4281 PR: Allow rest in commets to be colored differently from @language rest
  leo/config/leoSettings.leo
  leo/core/leoColorizer.py
  leo/modes/python.py
  leo/modes/rest_comments.py
  leo/modes/rust.py
Labels: Enhancement

#4286 PR: Improve promote-bodies
  leo/commands/editCommands.py
Labels: Enhancement

#4287 PR for #4284: Allow back slashes in find strings
  leo/core/leoFind.py
  leo/unittests/core/test_leoFind.py
Labels: Bug

#4291 PR: write-at-file-nodes always reports nodes
  leo/core/leoAtFile.py
Labels: Enhancement
