Repository leo-editor/leo-editor, pull requests merged in 2025-02, with the labels that each got.

#4294 PR for #4289: crash in leoTokens.py
  leo/core/leoTokens.py
  leo/unittests/core/test_leoTokens.py
Labels: Bug

#4298 Fix spurious error from createImporterData if '~/.leo/plugins' exists
  leo/core/leoApp.py
Labels: Bug

#4299 PR: Fix two quirps in the Rust importer
  leo/plugins/importers/rust.py
Labels: Code

#4303 Add minimal colorizer for Typst documents
  leo/core/leoApp.py
  leo/modes/typst.py
Labels: Enhancement
